name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # -----------------------------------------------------------
      # JOB 1: General Stats & Calendar
      # -----------------------------------------------------------
      - name: General Stats & Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, languages
          output_action: commit
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

      # -----------------------------------------------------------
      # JOB 2: LeetCode Stats
      # -----------------------------------------------------------
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: commit
          
          plugin_leetcode: yes
          plugin_leetcode_user: Atharva Shimpi
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_limit_skills: 6
          plugin_leetcode_limit_recent: 0 

      # -----------------------------------------------------------
      # JOB 3: Music (YouTube Music via Last.fm)
      # -----------------------------------------------------------
      - name: Music
        uses: lowlighter/metrics@latest
        with:
          filename: music.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: commit
          
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
          plugin_music_user: Atharva_Shimpi # <--- CHANGE THIS
          plugin_music_mode: recent
          plugin_music_limit: 4
